package ac.dia.pojo;
// Generated Jan 24, 2018 4:04:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="exam8_crud"
)
public class Product  implements java.io.Serializable {


     private Integer productId;
     private String productName;
     private String price;
     private String quantity;
     private String description;

    public Product() {
    }

	
    public Product(String productName, String price, String quantity) {
        this.productName = productName;
        this.price = price;
        this.quantity = quantity;
    }
    public Product(String productName, String price, String quantity, String description) {
       this.productName = productName;
       this.price = price;
       this.quantity = quantity;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="product_id", unique=true, nullable=false)
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    
    @Column(name="product_name", nullable=false, length=45)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="price", nullable=false, length=45)
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }

    
    @Column(name="quantity", nullable=false, length=45)
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="description", length=30)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


